name: Build Android Debug APK

on:
  push:
    branches:
      - dev   # Cambia “main” por la rama que tú uses

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # 1) Trae el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Instala Node.js (versión 18.x)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3) Instala dependencias JS con npm
      - name: Install dependencies
        run: npm ci

      # 4) Genera las carpetas nativas (en caso de estar en Managed Workflow)
      - name: Prebuild Expo (Managed → Bare)
        run: npx expo prebuild --platform android --no-install

      # 5) Compila el APK Debug con Gradle
      - name: Build Debug APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      # 6) Sube el APK Debug como artefacto de la Action
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
