# .github/workflows/android-debug.yml
name: Build Android Debug APK

on:
  push:
    branches:
      - dev   # O la rama que prefieras

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # 1) Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Instalar Node.js 18.x
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3) Instalar dependencias JS
      - name: Install dependencies
        run: npm ci

      # 4) Si tu proyecto es Expo Managed: generar carpetas android/ e ios/
      - name: Prebuild Expo (Managed → Bare)
        run: npx expo prebuild --platform android --no-install

      # 5) Compilar el APK Debug con Gradle
      - name: Build Debug APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      # 6) Listar la carpeta donde quedó el APK para que puedas verlo en logs
      - name: List generated APK
        run: |
          echo ">> El APK Debug generado está en: android/app/build/outputs/apk/debug/app-debug.apk"
          ls -l android/app/build/outputs/apk/debug/
